### PR TITLE
FIX: Fixes for api changes

### PR DESCRIPTION
**Pull request by Eric89GXL**
Complementary part to https://github.com/scitran/api/pull/36.

### CODE REVIEW

**Comment by gsfr** [comment]
Works as expected with scitran/api#36. CI failing, though.

**Comment by Eric89GXL** [comment]
Yep, I'd expect CI to fail until https://github.com/scitran/api/pull/36 lands in `master`.

**Comment by gsfr** [comment]
Of course. Sorry, I didn't think that through.

**Comment by Eric89GXL** [comment]
Rebased

**Comment by kofalt** [comment]
Sanity checks passed; merging both PRs.

**Pull request merged**
