### PR TITLE
MRG: Add mne

### PR DESCRIPTION
**Pull request by Eric89GXL**
Needed for MEG data. It's an easy dependency because it's pure python. It does require `scipy`, though, is that a problem? `scipy` is a bit of a beast to build...

### CODE REVIEW

**Comment by kofalt** [comment]
Hmm, CI is failing:

```
scripts/0-setup.sh: line 126: uuidgen: command not found

Flywheel: Generated default config file

Traceback (most recent call last):

  File "scripts/load-env.py", line 5, in <module>

    import toml

ImportError: No module named toml

Traceback (most recent call last):

  File "scripts/check-version.py", line 5, in <module>

    import pystache

ImportError: No module named pystache
```

The latest non-PR run did not have this problem, so I'm wondering if the Travis environment changed. 
I just pushed [a fix](https://github.com/scitran/scitran/commit/42eb147b5e22) for the uuidgen issue, rebase and retry?

Regarding libraries in general, I am a little uneasy having the API require any library required for any kind of scientific data - the steady state for that is not a happy place to be. Ideally we will start to get smarter about modules (multiple venvs? cascading? not a python expert) such that deployments use the minimum required for their instance.

But it's where we're at right now, so it doesn't sound unreasonable. @gsfr, thoughts?

**Comment by kofalt** [comment]
After a conversation with @gsfr it sounds like this wouldn't be a big deal; let's get CI working and merge.

**Comment by Eric89GXL** [comment]
I can work on the CI on Monday if you want.

**Comment by kofalt** [comment]
Sounds good. Not 100% sure why it's failing since this is such a tiny change; I currently have a PR going to remove some dumb pip hacks that I'm glad to be rid of, and maybe that'll help.

**Comment by kofalt** [comment]
#58 landed so I would definitely rebase onto that and see if CI likes you better now :)

**Comment by Eric89GXL** [comment]
Rebased. I still get the `pystache` error, which I find confusing. I'll look into it, though.

**Comment by kofalt** [comment]
Further up I think this is the culprit. Mne is not installing:

```
Collecting mne==0.9 (from -r requirements.txt (line 8))
  Downloading mne-0.9.0.tar.gz (4.9MB)
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-CNNaUH/mne/setup.py", line 11, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-CNNaUH/mne/setup.py", line 11, in <module>
    
        from numpy.distutils.core import setup
    
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CNNaUH/mne
```

**Comment by Eric89GXL** [comment]
Oh wow, missed that one...

**Comment by Eric89GXL** [comment]
@kofalt I ran into a problem building `scipy` from source because it took too long (> 10 minutes with no output). I changed the scripts to use wheels for `numpy` and `scipy` if it's running on Travis, which hopefully is safe enough for CI testing. Even though I've added `scipy` here, using wheels takes the Travis build time from 5+ minutes to about 3 minutes.

Ready for review/merge from my end.

**Comment by kofalt** [comment]
My knowledge of python packaging is incomplete; I hope you don't mind a few questions.

1. For this discussion, is reading http://pythonwheels.com sufficient for my understanding of wheel packaging? Are there other resources I should be aware of?

1. Under what conditions (if any) is a single wheel file portable across architectures? 
Are wheels pre-compiled for each architecture?

1. If yes, under what conditions (if any) is a C compiler required for installing?

1. Has the python community reached a consensus on wheels replacing other package types?

1. Are there any concerns about python 2 vs 3 that relate to using wheels?

1. Is there a convention around `requirements_*.txt`? What is the purpose of having a separate file?

1. Shouldn't the `scipy` entry in `requirements_1.txt` read `scipy==0.14`?

1. Could you link me to the python install docs on the various apt packages you've added? 
A [quick search](https://www.scipy.org/install.html) turned up different packages, but that looks to be for something else.

1. Any plans to migrate off plaintext transport for `travis-wheels.scikit-image.org`?

1. Is there a canonical hoster of python wheels? 

1. Could you link me to the build script for `travis-wheels.scikit-image.org`'s wheels?

---

Reading the info site I linked above, my preliminary opinion is that wheel packaging sounds roundly superior. I would like to fitness-evaluate using that option and do one of two things:

* Use wheels unconditionally for all installs & all packages that support it
* Add the [official travis workaround](http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received) to avoid cancelling quiet jobs.

The second option is less change and will be easier to land, which consists of adding `travis_wait` to the last line of our travis config. As it currently stands, I reran the previously-failing cb3fbcd commit, and this time it passed by virtue of being slightly faster. 

It would be great to bypass utterly redundant compile times on install, so I'm open to using wheels. At minimum, we'd need a secure transport for providing them (we have one if needed) and a way to reproduce the builds. Far more ideally, the python community would canonically host them.

**Comment by Eric89GXL** [comment]
> For this discussion, is reading http://pythonwheels.com sufficient for my understanding of wheel packaging? Are there other resources I should be aware of?

I actually haven't extensively used wheels, but developers I trust do. So I guess we'll have to learn about it together.

> Under what conditions (if any) is a single wheel file portable across architectures? Are wheels pre-compiled for each architecture?

They can be compiled for each architecture, but from what I have seen, they are not always compiled for each architecture.

> If yes, under what conditions (if any) is a C compiler required for installing?

One of the strengths is that this compilation can be avoided altogether.

> Has the python community reached a consensus on wheels replacing other package types?

I see them used a lot for making Travis-CI run faster. Basically wheels and Anaconda show up in all the Python repos I look at.

> Are there any concerns about python 2 vs 3 that relate to using wheels?

I don't think so, you can release different ones for the two different versions.

> Is there a convention around requirements_*.txt? What is the purpose of having a separate file?

They had to be separated because `numpy` needed to be installed *before* `mne` could be. When running a single `requirements.txt` through `pip`, there were errors on the `mne` step because `numpy` wasn't installed, and it was imported in `mne`'s `setup.py` script. I can add a comment to clarify this if it helps.

> Shouldn't the scipy entry in requirements_1.txt read scipy==0.14?

The only thing that requires `scipy` currently is `mne`, and it has pretty loose `scipy` requirements (>=0.11, I think) and we're pretty good about ensuring forward compatibility. So it seemed simpler not to constrain which version, and just ensure that *some* version got installed.

> Could you link me to the python install docs on the various apt packages you've added? 

These are required to build `scipy`, without them it can't be built from source. I took the list from the `scipy` Travis CI build:

https://github.com/scipy/scipy/blob/master/.travis.yml#L64

> Any plans to migrate off plaintext transport for travis-wheels.scikit-image.org?

I don't know, I've only considered using it for installing to Travis, where security is less of an issue than it would be for end users.

> Is there a canonical hoster of python wheels?

I suspect there is not one for `linux` builds of `numpy` and `scipy`. I pulled that wheels URL from `nibabel`'s `.travis.yml`:

https://github.com/nipy/nibabel/blob/master/.travis.yml#L51

`nibabel` is run by Matthew Brett, who IIRC builds wheels for `scipy`, so my assumption was that he made use of the easiest/simplest/best source for Travis CI wheels in his Travis config. Notably, you can access it via `https` but the certificate is invalid or self-signed, so it might not help much.

> Could you link me to the build script for travis-wheels.scikit-image.org's wheels?

I think this is it: https://github.com/scikit-image/scikit-image-wheels

> I would like to fitness-evaluate using that option and do one of two things:
>
> * Use wheels unconditionally for all installs & all packages that support it
> * Add the official travis workaround to avoid cancelling quiet jobs.

The first option doesn't sound viable for now, since I don't think wheels are built for all platforms. We can ping Matthew about it if we want an actual answer, though.

The second one isn't great, because building `scipy` takes > 10 minutes, so the CI build time minimums would jump quite a bit. And this is mostly wasted time, because it's spending time testing the `scipy` build instead of `scitran`, which is a bummer.

My proposal is a third option, which is to have a different behavior for Travis than users, which is to use the insecure wheels instead of a system build. It's certainly not as simple a solution as using the same `numpy` and `scipy` versions in both scenarios, but that additional complication is worth the decreased build time in my mind. For me Travis time has become a really frustrating issue in the past, so I try to do everything I can to speed it up now.

**Comment by Eric89GXL** [comment]
Would it work for now to use `scikit-image` wheels for Travis, and at some point in the future move to `scitran`-hosted wheels for the necessary packages? That way the builds can be sped up on Travis, and in the longer term could be sped up for users setting things up later.

**Comment by Eric89GXL** [comment]
Actually -- I think we'd just need to build wheels for Ubuntu 14.04 x86_64, right? If that's the case, I might be able to spin up a 14.04 server VM and build the wheels, and put them on a UW server for testing purposes. Once I got/get it working, we could move them to you guys hosting them. WDYT?

**Comment by Eric89GXL** [comment]
Hmm, actually since `numpy` and `scipy` are compiled, I don't think we can easily provide wheels for them. We could use the system site packages `python-numpy` and `python-scipy`, but then we can't pick particular versions, and also have to allow using other site packages, etc.

**Comment by kofalt** [comment]
I appreciate the verbose response - this is exactly the information I needed.

Personally I try to avoid `if CI then edge case` stuff in install scripts, but it would also be a waste to burn 10 minutes of CPU per push over a dependency. We burn plenty CPU time on install already :sunglasses: 

Since we have a clear resolution for wheel hosting problems (adding `travis_wait`) I'm amicable to your solution. Let's go with this for now. I would be open to a conversation about automatically building a variety of wheel files to speed up our installs - email me at nathanielkofalt@invenshure.com and let's chat!

**Comment by Eric89GXL** [comment]
Alright. I built some for 14.04, forgetting at first that Travis still runs 12.04. I guess we'll have to see if those work for Travis, and also e.g. on my 15.04 system.

So is the plan to merge this for now, and then iterate with wheels if we can? Or did you want to avoid the Travis-exceptional behavior? If we keep it as is, we don't need to add `travis_wait`.

**Comment by kofalt** [comment]
Yes, to clarify I intend to merge this momentarily - I'm waiting for python to complete locally :laughing: 

We can chat via email about building wheels.

**Comment by Eric89GXL** [comment]
Sounds good. If you sign up for `gitter` (free / github auth) it's also easy to have private chats there. Unless I see you on `gitter`, I'll send an email tomorrow or Monday -- I can do a little bit of `wheel` testing locally to assess feasibility so we have a bit more information.

**Comment by kofalt** [comment]
That would be great. We have used gitter in the past; personally I found their web client very irritating and slow. I've been meaning to set up an IRC bouncer so that I can idle in scitran/scitran.

Perhaps next week. In the meantime, email or another ticket will work. 

My ideal scenario would be building wheels for any package possible for linux x64, and conditionally using those on install if the arch matches. If you have formulas to produce wheels (sorry I have not looked extensively at the builder repo you linked) I'd be very content either building them locally or putting them on our Jenkins server internally + hosting them via google's storage browser (public downloads + SSL).

**Comment by Eric89GXL** [comment]
Sounds good

**Pull request merged**
