### PR TITLE
OS X infra

### PR DESCRIPTION
**Pull request by gsfr**
@kofalt This is an attempt to address #35.

Sorry for the huge diff due to tab-to-space conversion. The first commit is just that. Second commit is actual code change.

I got as far as getting ```./live.sh setup``` to complete successfully on OS X, but haven't tested on Linux. I'm now installing Go, Mongo, and Nginx directly into the virtual env. Seems clean and logical to me to leverage that as our root filesystem. Certainly open to discussion, though. We might take this as far as having the venv pretty much replace ```persistent``` and ```code```.

### CODE REVIEW

**Comment by kofalt** [comment]
The venv is the only part of the persistent directory that contains absolute paths & is not `mv` compatible; for that reason, I don't think putting anything beyond python packages in there is a good idea. 

Looks like a good start otherwise.

**Comment by kofalt** [comment]
I wish you hadn't changed indentation as part of this PR, as it'll be difficult to do any work simultaneously with this branch. As it stands currently, that won't be a problem.

**Comment by gsfr** [comment]
Changing the indentation was not my intent, but my editor did it on the lines I touched and that got rather messy. Didn't think too much about it, but we could just merge that commit into master right now.

Also didn't plan on upgrading golang, but the previous version had multiple packages for various flavors of OS X. Didn't seem like a big deal to me. Is it?

Good point on the absolute path virtual env mess. Other than that, I like the result. You?

There is a ```--relocatable``` flag for ```virtualenv```. We could try running that at the end and seeing if the result still works.

**Comment by kofalt** [comment]
Whelp. Our editors are now at war... we should figure this out. Ugh.
Sublime can be configured to detect indentation; I thought I had that turned off for a good reason.

Golang upgrades are probably some of the least-disruptive incremental language releases; a crude summary of 1.4.x to 1.5.x is that the runtime got faster and the compiler got slower (~2x). Unlikely to cause problems; some possibles are listed below.

Regarding venv consolidation, I'd be against it even if we fixed absolute paths - while I have tried my best to make as much of this setup reasonable & idempotent as possible, it's a leaky abstraction, and frequently deleting some subset of the `persistent` directory is the solution. We might want to reorganize the `persistent` directory in general (I've been thinking the `persistent/setup` folder is the right way to lay things out), but it should be for clear reasons worth triggering a re-install.

---

Philosophically, it's important to me that a PR has a strictly limited scope for change.
For example - from these changes:

1. I don't think reflex will be refetched or rebuilt for users who get this change. Will that bite us later?
1. Reflex is using some lower-level file I/O stuff, is it worth checking that library's docs?
1. What are the effects of nginx configure changes for linux as non-root, and linux as root?
1. If for any reason `nginx` and etc binaries are not in the venv, will the new scripting behave correctly, or potentially make a call outside the persistent folder?

Which is a lot of stuff to figure out beyond #35. In general, I'll be unenthusiastic about PR changes that deviate from it's core purpose - though I think several of these would make good discussion tickets, etc.

**Comment by kofalt** [comment]
Our strategy regarding OSX support is under discussion and the strategy will likely be different.
Closing this pending a revival.

**Pull request closed without merging**
