### PR TITLE
ENH: Add pylint

### PR DESCRIPTION
**Pull request by Eric89GXL**
~~This should error out due to `pylint` checks.~~
Style has been fixed.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Travis is happy, style issues with `scripts/*.py` fixed. I changed the line-length max to 120, @gsfr let me know if that sounds about right to you. It looks good on my screen.

Ready for review/merge from my end.

**Comment by gsfr** [comment]
I've got my editor set to 150, so most code should fit into that. Let's start with that. Should be pretty painless.

**Comment by Eric89GXL** [comment]
@gsfr done. Happy otherwise?

**Comment by gsfr** [comment]
LGTM. @kofalt?

**Comment by kofalt** [comment]
Sorry guys, I'll be intermittently high latency for awhile: working on a bunch of other stuff that's time-sensitive. My ambition will be to review all outstanding PRs on either Friday or (more likely) Monday.

**Comment by Eric89GXL** [comment]
Thanks for the heads up, no rush from my end.

**Comment by kofalt** [comment]
This looks great :+1: Looking forward to generalizing this for all our python source.

**Pull request merged**
