### PR TITLE
Target reconfiguration for production-friendly usage

### PR DESCRIPTION
**Pull request by kofalt**
From earlier conversation: 

* No-arg launch target will now be an explicit run target; no-arg will print usage.

* The setup target will carry out its current functions, minus the bootstrapping. No prompts; will print shared secret and now-configure blurb.

* Add configure target. If arg passed, is CSV; consume. If not, prompt for 1 user. Bootstrap.

This PR does everything sans the CSV consumption, which I'll leave for another day. Saved as #50.

---

It is now possible to boot a new instance without any users or data, which is easier for new production rollouts. Initial steps are separated into a non-prompting `./live.sh setup` portion and an interactive `./live.sh configure` portion. Documentation updated to reflect this.

Pinging @gsfr for review.

### CODE REVIEW

**Comment by gsfr** [comment]
Should we change the default for ```site.insecure``` to ```false```, or at least print a warning on ```run``` in case of ```true```?
Is the shared secret autogen in another branch?

**Comment by kofalt** [comment]
Good points.

The script now defaults `site.insecure` off, and generates a random secret on template copy.

**Comment by gsfr** [comment]
LGTM. Feel free to rebase and merge.

**Comment by kofalt** [comment]
Rebased & CI is green; merging.

**Pull request merged**
